[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["mupdf"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
